### ISSUE TITLE
About the desktop version

### ISSUE THREAD

**Issue by Jzow** [kpreid/all-is-cubes#266]
I want to ask what kind of crate the desktop version uses, i know that [Tauri](https://github.com/tauri-apps/tauri) is not bad at present

**Comment by kpreid** [comment]
`all-is-cubes-desktop` uses custom 3D rendering into native windows; it is currently capable of using either [`luminance`](https://docs.rs/luminance/latest/luminance/) or [`wgpu`](https://wgpu.rs/) as rendering APIs. All of the user interface (what little of it there is so far) is [implemented within the 3D environment](https://github.com/kpreid/all-is-cubes/tree/main/all-is-cubes/src/vui/).

This was an intentional design choice to avoid platform entanglement; the web and desktop versions have nearly identical UI without any additional platform abstraction layer needed. Of course, the disadvantage is that the UI lacks accessibility API support, versatile text rendering, and other things; and has to be implemented from scratch. In the future I might revisit the question of including native UI, especially for such things as text entry.
